#!/usr/bin/env bash

EDITOR=${EDITOR:-nvim}
VIEW=zathura
TERMINAL=${TERMINAL:-kitty}
Menu="dmenu -c -p"

# <<------ Directories ------>> #
book_library="/path/to/books/"
note_library="/path/to/notes/"
template_library="/path/to/note/templates/"
article_library="/path/to/articles/"

# <<------ Options ------>> #
declare -A actions
actions["📑 Create Note"]=$template_library
actions["🔖 View Notes"]=$note_library
actions["📚 Books"]=$book_library
actions["📜 Articles"]=$article_library

# <<------ Main ------>> #
create_document() {
  document_type=$(echo -e "Basic\nLaTeX\nBeamer\nRmark" | $Menu "What kind of note?")

  if [ -z "$document_type" ]; then
    return
  fi

  case "$document_type" in
  Basic)
    template="SimpleNote.md"
    EXTENSION="md"
    message="Basic Document Created!"
    ;;
  LaTeX)
    template="LaTeX.tex"
    EXTENSION="tex"
    message="LaTeX Document Created!"
    ;;
  Beamer)
    template="Presentation.tex"
    EXTENSION="tex"
    message="Beamer Presentation Created!"
    ;;
  Rmark)
    template="RMarkdown.rmd"
    EXTENSION="rmd"
    message="R Markdown Document Created!"
    ;;
  *)
    echo "Invalid option"
    return 1
    ;;
  esac

  cn_name=$($Menu "Enter a name for the note:")

  if [ -z "$cn_name" ]; then
    return
  fi

  if [ -f "$directory/$cn_name.$EXTENSION" ]; then
    if ! (echo -e "Yes\nNo" | $Menu "Note already exists. Overwrite?" | grep -q "Yes"); then
      return
    fi
  fi

  notify-send "$message"
  cp "$directory/Templates/$template" "$directory/$cn_name.$EXTENSION"
  "$TERMINAL" -e "$EDITOR" "$directory/$cn_name.$EXTENSION"
}

open_document() {
  FILE=$(find "$directory" -type f \( -name "*.epub" -o -name "*.pdf" \) -printf "%f\n" | $Menu "Select Document:")
  if [[ -n "$FILE" ]]; then
    FULL_PATH=$(find "$directory" -type f -name "$FILE" -print -quit)
    $VIEW "$FULL_PATH"
  fi
}

edit_notes() {
  FILE=$(find "$directory" -type f -name "*.md" -printf "%f\n" | $Menu "Select Note:")
  if [[ -n "$FILE" ]]; then
    FULL_PATH=$(find "$directory" -type f -name "$FILE" -print -quit)
    $TERMINAL -e "$EDITOR" "$FULL_PATH"
  fi
}

main() {
  selected_action=$(printf '%s\n' "${!actions[@]}" | $Menu "📂 Choose an action:")

  if [ -z "$selected_action" ]; then
    exit 0
  fi

  selected_dir_or_func="${actions[$selected_action]}"

  if [ "$selected_dir_or_func" = "download_books" ]; then
    $selected_dir_or_func
  else
    directory="$selected_dir_or_func"
    case $selected_action in
    "📑 Create Note")
      create_document
      ;;
    "🔖 View Notes")
      edit_notes
      ;;
    "📚 Books" | "📜 Articles")
      open_document
      ;;
    esac
  fi
}

main
